services:

  omping-a:
    image: husarion/omping
    network_mode: service:husarnet-a
    restart: on-failure
    tty: true
    command: a b

  husarnet-a:
    image: husarnet/husarnet
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment: 
      - HOSTNAME=a
      - JOINCODE=${JOINCODE:?you need to create .env file with a JOINCODE variable}